#File format
version: '3'

services:

 library_db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: book
      MYSQL_USER: bookeeper
      MYSQL_PASSWORD: b00kEEper
      
    ports:
      - "3308:3306"
      
 adminer:
    image: adminer
    restart: always
    environment:
        ADMINER_DEFAULT_SERVER: library_db
    ports:
      - 8080:8080
      